### ISSUE TITLE
Find good dialog audio volume

### ISSUE THREAD

**Issue by Flam3sDOTA** [ModDota/dota-tutorial#278]
Despite lowering the game audio to 30%, their audio is still too loud. Revert the latest audio volume change please.

**Comment by RobinKa** [comment]
Renamed the issue since there was no consensus on this. When testing I reset the audio settings to their default (as a new player would probably have) which puts all the bars at 100%. The volume was then fine for me with the current changes (eg. try having some music open while playing the game to compare).

**Comment by Shushishtok** [comment]
Personally I have no issues with the current level of volume, not too loud not too quite.

**Comment by quickcharge3** [comment]
there was a player suggestion to mute DKs voicelines while dialog is playing, good idea imo

**Comment by Shushishtok** [comment]
Closed, it sounds fine.
